using SpaceTraders.Models.Enums;

namespace SpaceTraders.Models;

public static class MaterialMap
{
    private static readonly List<TradeSymbolsEnum> SHIP_IMPORTS = [TradeSymbolsEnum.SHIP_PLATING, TradeSymbolsEnum.SHIP_PARTS];

    public static readonly Dictionary<TradeSymbolsEnum, List<TradeSymbolsEnum>> tradeMap = new()
    {
        [TradeSymbolsEnum.LIQUID_HYDROGEN] = [TradeSymbolsEnum.MACHINERY],
        [TradeSymbolsEnum.LIQUID_NITROGEN] = [TradeSymbolsEnum.MACHINERY],
        [TradeSymbolsEnum.HYDROCARBON] = [TradeSymbolsEnum.MACHINERY],
        [TradeSymbolsEnum.AMMONIA_ICE] = [TradeSymbolsEnum.MACHINERY],
        [TradeSymbolsEnum.ICE_WATER] = [TradeSymbolsEnum.MACHINERY],

        [TradeSymbolsEnum.PRECIOUS_STONES] = [TradeSymbolsEnum.EXPLOSIVES],
        [TradeSymbolsEnum.QUARTZ_SAND] = [TradeSymbolsEnum.EXPLOSIVES],
        [TradeSymbolsEnum.SILICON_CRYSTALS] = [TradeSymbolsEnum.EXPLOSIVES],
        [TradeSymbolsEnum.IRON_ORE] = [TradeSymbolsEnum.EXPLOSIVES],
        [TradeSymbolsEnum.ALUMINUM_ORE] = [TradeSymbolsEnum.EXPLOSIVES],
        [TradeSymbolsEnum.SILVER_ORE] = [TradeSymbolsEnum.EXPLOSIVES],
        [TradeSymbolsEnum.COPPER_ORE] = [TradeSymbolsEnum.EXPLOSIVES],
        [TradeSymbolsEnum.PLATINUM_ORE] = [TradeSymbolsEnum.EXPLOSIVES],
        [TradeSymbolsEnum.GOLD_ORE] = [TradeSymbolsEnum.EXPLOSIVES],
        [TradeSymbolsEnum.URANITE_ORE] = [TradeSymbolsEnum.EXPLOSIVES],
        [TradeSymbolsEnum.MERITIUM_ORE] = [TradeSymbolsEnum.EXPLOSIVES],
        [TradeSymbolsEnum.DIAMONDS] = [TradeSymbolsEnum.EXPLOSIVES],

        [TradeSymbolsEnum.SHIP_SALVAGE] = [TradeSymbolsEnum.MACHINERY],
        [TradeSymbolsEnum.CULTURAL_ARTIFACTS] = [TradeSymbolsEnum.LAB_INSTRUMENTS],

        [TradeSymbolsEnum.PLASTICS] = [TradeSymbolsEnum.LIQUID_HYDROGEN],
        [TradeSymbolsEnum.FERTILIZERS] = [TradeSymbolsEnum.LIQUID_NITROGEN],
        [TradeSymbolsEnum.FUEL] = [TradeSymbolsEnum.HYDROCARBON],
        [TradeSymbolsEnum.IRON] = [TradeSymbolsEnum.IRON_ORE],
        [TradeSymbolsEnum.ALUMINUM] = [TradeSymbolsEnum.ALUMINUM_ORE],
        [TradeSymbolsEnum.POLYNUCLEOTIDES] = [TradeSymbolsEnum.LIQUID_HYDROGEN, TradeSymbolsEnum.LIQUID_NITROGEN],
        [TradeSymbolsEnum.EXPLOSIVES] = [TradeSymbolsEnum.LIQUID_HYDROGEN, TradeSymbolsEnum.LIQUID_NITROGEN],
        [TradeSymbolsEnum.COPPER] = [TradeSymbolsEnum.COPPER_ORE],
        [TradeSymbolsEnum.SILVER] = [TradeSymbolsEnum.SILVER_ORE],
        [TradeSymbolsEnum.PLATINUM] = [TradeSymbolsEnum.PLATINUM_ORE],
        [TradeSymbolsEnum.GOLD] = [TradeSymbolsEnum.GOLD_ORE],
        [TradeSymbolsEnum.URANITE] = [TradeSymbolsEnum.URANITE_ORE],
        [TradeSymbolsEnum.MERITIUM] = [TradeSymbolsEnum.MERITIUM_ORE],

        [TradeSymbolsEnum.AMMUNITION] = [TradeSymbolsEnum.IRON, TradeSymbolsEnum.LIQUID_NITROGEN],
        [TradeSymbolsEnum.FAB_MATS] = [TradeSymbolsEnum.IRON, TradeSymbolsEnum.QUARTZ_SAND],
        [TradeSymbolsEnum.FOOD] = [TradeSymbolsEnum.FERTILIZERS],
        [TradeSymbolsEnum.FABRICS] = [TradeSymbolsEnum.FERTILIZERS],
        [TradeSymbolsEnum.ELECTRONICS] = [TradeSymbolsEnum.SILICON_CRYSTALS, TradeSymbolsEnum.COPPER],
        [TradeSymbolsEnum.MACHINERY] = [TradeSymbolsEnum.IRON],
        [TradeSymbolsEnum.EQUIPMENT] = [TradeSymbolsEnum.ALUMINUM, TradeSymbolsEnum.PLASTICS],
        [TradeSymbolsEnum.JEWELRY] = [TradeSymbolsEnum.GOLD, TradeSymbolsEnum.SILVER, TradeSymbolsEnum.PRECIOUS_STONES, TradeSymbolsEnum.DIAMONDS],
        [TradeSymbolsEnum.MICROPROCESSORS] = [TradeSymbolsEnum.SILICON_CRYSTALS, TradeSymbolsEnum.COPPER],
        [TradeSymbolsEnum.FIREARMS] = [TradeSymbolsEnum.IRON, TradeSymbolsEnum.AMMUNITION],
        [TradeSymbolsEnum.ASSAULT_RIFLES] = [TradeSymbolsEnum.ALUMINUM, TradeSymbolsEnum.AMMUNITION],

        [TradeSymbolsEnum.CLOTHING] = [TradeSymbolsEnum.FABRICS],
        [TradeSymbolsEnum.SHIP_PLATING] = [TradeSymbolsEnum.ALUMINUM, TradeSymbolsEnum.MACHINERY],
        [TradeSymbolsEnum.SHIP_PARTS] = [TradeSymbolsEnum.EQUIPMENT, TradeSymbolsEnum.ELECTRONICS],
        [TradeSymbolsEnum.MEDICINE] = [TradeSymbolsEnum.FABRICS, TradeSymbolsEnum.POLYNUCLEOTIDES],
        [TradeSymbolsEnum.DRUGS] = [TradeSymbolsEnum.AMMONIA_ICE, TradeSymbolsEnum.POLYNUCLEOTIDES],
        [TradeSymbolsEnum.MILITARY_EQUIPMENT] = [TradeSymbolsEnum.ALUMINUM, TradeSymbolsEnum.ELECTRONICS],
        [TradeSymbolsEnum.LAB_INSTRUMENTS] = [TradeSymbolsEnum.ELECTRONICS, TradeSymbolsEnum.EQUIPMENT],
        [TradeSymbolsEnum.BIOCOMPOSITES] = [TradeSymbolsEnum.FABRICS, TradeSymbolsEnum.POLYNUCLEOTIDES],
        [TradeSymbolsEnum.ADVANCED_CIRCUITRY] = [TradeSymbolsEnum.ELECTRONICS, TradeSymbolsEnum.MICROPROCESSORS],
        [TradeSymbolsEnum.REACTOR_SOLAR_I] = [TradeSymbolsEnum.IRON, TradeSymbolsEnum.MACHINERY],
        [TradeSymbolsEnum.REACTOR_FUSION_I] = [TradeSymbolsEnum.IRON, TradeSymbolsEnum.MACHINERY],
        [TradeSymbolsEnum.REACTOR_FISSION_I] = [TradeSymbolsEnum.IRON, TradeSymbolsEnum.MACHINERY],
        [TradeSymbolsEnum.REACTOR_CHEMICAL_I] = [TradeSymbolsEnum.IRON, TradeSymbolsEnum.MACHINERY],
        [TradeSymbolsEnum.REACTOR_ANTIMATTER_I] = [TradeSymbolsEnum.IRON, TradeSymbolsEnum.MACHINERY],
        [TradeSymbolsEnum.ENGINE_IMPULSE_DRIVE_I] = [TradeSymbolsEnum.IRON, TradeSymbolsEnum.MACHINERY],
        [TradeSymbolsEnum.ENGINE_ION_DRIVE_I] = [TradeSymbolsEnum.IRON, TradeSymbolsEnum.MACHINERY],
        [TradeSymbolsEnum.MODULE_CARGO_HOLD_I] = [TradeSymbolsEnum.IRON, TradeSymbolsEnum.MACHINERY],
        [TradeSymbolsEnum.MODULE_CARGO_HOLD_II] = [TradeSymbolsEnum.ALUMINUM, TradeSymbolsEnum.MACHINERY],
        [TradeSymbolsEnum.MODULE_MINERAL_PROCESSOR_I] = [TradeSymbolsEnum.IRON, TradeSymbolsEnum.MACHINERY],
        [TradeSymbolsEnum.MODULE_GAS_PROCESSOR_I] = [TradeSymbolsEnum.IRON, TradeSymbolsEnum.MACHINERY],
        [TradeSymbolsEnum.MODULE_CREW_QUARTERS_I] = [TradeSymbolsEnum.IRON, TradeSymbolsEnum.MACHINERY, TradeSymbolsEnum.FABRICS],
        [TradeSymbolsEnum.MODULE_ENVOY_QUARTERS_I] = [TradeSymbolsEnum.IRON, TradeSymbolsEnum.MACHINERY, TradeSymbolsEnum.FABRICS],
        [TradeSymbolsEnum.MODULE_PASSENGER_CABIN_I] = [TradeSymbolsEnum.IRON, TradeSymbolsEnum.MACHINERY, TradeSymbolsEnum.FABRICS],
        [TradeSymbolsEnum.MODULE_SCIENCE_LAB_I] = [TradeSymbolsEnum.PLATINUM, TradeSymbolsEnum.MACHINERY, TradeSymbolsEnum.ADVANCED_CIRCUITRY],
        [TradeSymbolsEnum.MODULE_ORE_REFINERY_I] = [TradeSymbolsEnum.PLATINUM, TradeSymbolsEnum.MACHINERY],
        [TradeSymbolsEnum.MODULE_FUEL_REFINERY_I] = [TradeSymbolsEnum.PLATINUM, TradeSymbolsEnum.MACHINERY],
        [TradeSymbolsEnum.MODULE_MICRO_REFINERY_I] = [TradeSymbolsEnum.PLATINUM, TradeSymbolsEnum.MACHINERY],
        [TradeSymbolsEnum.MOUNT_GAS_SIPHON_I] = [TradeSymbolsEnum.IRON, TradeSymbolsEnum.MACHINERY],
        [TradeSymbolsEnum.MOUNT_GAS_SIPHON_II] = [TradeSymbolsEnum.ALUMINUM, TradeSymbolsEnum.MACHINERY],
        [TradeSymbolsEnum.MOUNT_SURVEYOR_I] = [TradeSymbolsEnum.IRON, TradeSymbolsEnum.MACHINERY, TradeSymbolsEnum.ELECTRONICS],
        [TradeSymbolsEnum.MOUNT_SURVEYOR_II] = [TradeSymbolsEnum.ALUMINUM, TradeSymbolsEnum.MACHINERY, TradeSymbolsEnum.ELECTRONICS],
        [TradeSymbolsEnum.MOUNT_SENSOR_ARRAY_I] = [TradeSymbolsEnum.IRON, TradeSymbolsEnum.MACHINERY, TradeSymbolsEnum.ELECTRONICS],
        [TradeSymbolsEnum.MOUNT_SENSOR_ARRAY_II] = [TradeSymbolsEnum.ALUMINUM, TradeSymbolsEnum.MACHINERY, TradeSymbolsEnum.ELECTRONICS],
        [TradeSymbolsEnum.MOUNT_MINING_LASER_I] = [TradeSymbolsEnum.IRON, TradeSymbolsEnum.MACHINERY, TradeSymbolsEnum.DIAMONDS],
        [TradeSymbolsEnum.MOUNT_MINING_LASER_II] = [TradeSymbolsEnum.ALUMINUM, TradeSymbolsEnum.MACHINERY, TradeSymbolsEnum.DIAMONDS],
        [TradeSymbolsEnum.MOUNT_TURRET_I] = [TradeSymbolsEnum.IRON, TradeSymbolsEnum.MACHINERY],
        [TradeSymbolsEnum.MOUNT_LASER_CANNON_I] = [TradeSymbolsEnum.IRON, TradeSymbolsEnum.MACHINERY, TradeSymbolsEnum.DIAMONDS],
        [TradeSymbolsEnum.MOUNT_MISSILE_LAUNCHER_I] = [TradeSymbolsEnum.IRON, TradeSymbolsEnum.MACHINERY],

        [TradeSymbolsEnum.QUANTUM_STABILIZERS] = [TradeSymbolsEnum.PLATINUM, TradeSymbolsEnum.ADVANCED_CIRCUITRY, TradeSymbolsEnum.URANITE],
        [TradeSymbolsEnum.ANTIMATTER] = [TradeSymbolsEnum.LAB_INSTRUMENTS, TradeSymbolsEnum.ADVANCED_CIRCUITRY],
        [TradeSymbolsEnum.EXOTIC_MATTER] = [TradeSymbolsEnum.LAB_INSTRUMENTS, TradeSymbolsEnum.ADVANCED_CIRCUITRY],
        [TradeSymbolsEnum.RELIC_TECH] = [TradeSymbolsEnum.LAB_INSTRUMENTS, TradeSymbolsEnum.EQUIPMENT],
        [TradeSymbolsEnum.NOVEL_LIFEFORMS] = [TradeSymbolsEnum.LAB_INSTRUMENTS, TradeSymbolsEnum.EQUIPMENT],
        [TradeSymbolsEnum.BOTANICAL_SPECIMENS] = [TradeSymbolsEnum.LAB_INSTRUMENTS, TradeSymbolsEnum.EQUIPMENT],
        [TradeSymbolsEnum.AI_MAINFRAMES] = [TradeSymbolsEnum.ADVANCED_CIRCUITRY, TradeSymbolsEnum.MICROPROCESSORS],
        [TradeSymbolsEnum.QUANTUM_DRIVES] = [TradeSymbolsEnum.ADVANCED_CIRCUITRY, TradeSymbolsEnum.URANITE],
        [TradeSymbolsEnum.GRAVITON_EMITTERS] = [TradeSymbolsEnum.ADVANCED_CIRCUITRY, TradeSymbolsEnum.MERITIUM],
        [TradeSymbolsEnum.ROBOTIC_DRONES] = [TradeSymbolsEnum.ADVANCED_CIRCUITRY, TradeSymbolsEnum.ALUMINUM],
        [TradeSymbolsEnum.CYBER_IMPLANTS] = [TradeSymbolsEnum.ADVANCED_CIRCUITRY, TradeSymbolsEnum.BIOCOMPOSITES],
        [TradeSymbolsEnum.NANOBOTS] = [TradeSymbolsEnum.POLYNUCLEOTIDES, TradeSymbolsEnum.LAB_INSTRUMENTS],
        [TradeSymbolsEnum.GENE_THERAPEUTICS] = [TradeSymbolsEnum.POLYNUCLEOTIDES, TradeSymbolsEnum.LAB_INSTRUMENTS],
        [TradeSymbolsEnum.NEURAL_CHIPS] = [TradeSymbolsEnum.POLYNUCLEOTIDES, TradeSymbolsEnum.ADVANCED_CIRCUITRY],
        [TradeSymbolsEnum.MOOD_REGULATORS] = [TradeSymbolsEnum.POLYNUCLEOTIDES, TradeSymbolsEnum.LAB_INSTRUMENTS],
        [TradeSymbolsEnum.VIRAL_AGENTS] = [TradeSymbolsEnum.POLYNUCLEOTIDES, TradeSymbolsEnum.LAB_INSTRUMENTS],
        [TradeSymbolsEnum.MICRO_FUSION_GENERATORS] = [TradeSymbolsEnum.ADVANCED_CIRCUITRY, TradeSymbolsEnum.PLATINUM, TradeSymbolsEnum.DIAMONDS],
        [TradeSymbolsEnum.SUPERGRAINS] = [TradeSymbolsEnum.FERTILIZERS, TradeSymbolsEnum.POLYNUCLEOTIDES, TradeSymbolsEnum.LAB_INSTRUMENTS],
        [TradeSymbolsEnum.LASER_RIFLES] = [TradeSymbolsEnum.DIAMONDS, TradeSymbolsEnum.PLATINUM, TradeSymbolsEnum.ADVANCED_CIRCUITRY],
        [TradeSymbolsEnum.HOLOGRAPHICS] = [TradeSymbolsEnum.GOLD, TradeSymbolsEnum.SILVER, TradeSymbolsEnum.ADVANCED_CIRCUITRY],
        [TradeSymbolsEnum.ENGINE_ION_DRIVE_II] = [TradeSymbolsEnum.PLATINUM, TradeSymbolsEnum.ADVANCED_CIRCUITRY],
        [TradeSymbolsEnum.ENGINE_HYPER_DRIVE_I] = [TradeSymbolsEnum.PLATINUM, TradeSymbolsEnum.ADVANCED_CIRCUITRY],
        [TradeSymbolsEnum.MODULE_CARGO_HOLD_III] = [TradeSymbolsEnum.PLATINUM, TradeSymbolsEnum.MACHINERY, TradeSymbolsEnum.ADVANCED_CIRCUITRY],
        [TradeSymbolsEnum.MODULE_JUMP_DRIVE_I] = [TradeSymbolsEnum.IRON, TradeSymbolsEnum.ADVANCED_CIRCUITRY],
        [TradeSymbolsEnum.MODULE_JUMP_DRIVE_II] = [TradeSymbolsEnum.PLATINUM, TradeSymbolsEnum.ADVANCED_CIRCUITRY, TradeSymbolsEnum.GOLD],
        [TradeSymbolsEnum.MODULE_JUMP_DRIVE_III] = [
           TradeSymbolsEnum.PLATINUM,
           TradeSymbolsEnum.ADVANCED_CIRCUITRY,
           TradeSymbolsEnum.GOLD,
           TradeSymbolsEnum.MERITIUM,
           ],
        [TradeSymbolsEnum.MODULE_WARP_DRIVE_I] = [TradeSymbolsEnum.IRON, TradeSymbolsEnum.ADVANCED_CIRCUITRY],
        [TradeSymbolsEnum.MODULE_WARP_DRIVE_II] = [TradeSymbolsEnum.PLATINUM, TradeSymbolsEnum.ADVANCED_CIRCUITRY, TradeSymbolsEnum.URANITE],
        [TradeSymbolsEnum.MODULE_WARP_DRIVE_III] = [
           TradeSymbolsEnum.PLATINUM,
           TradeSymbolsEnum.ADVANCED_CIRCUITRY,
           TradeSymbolsEnum.MERITIUM,
           TradeSymbolsEnum.MERITIUM,
          ],
        [TradeSymbolsEnum.MOUNT_GAS_SIPHON_III] = [TradeSymbolsEnum.PLATINUM, TradeSymbolsEnum.MACHINERY, TradeSymbolsEnum.ADVANCED_CIRCUITRY],
        [TradeSymbolsEnum.MODULE_SHIELD_GENERATOR_I] = [TradeSymbolsEnum.IRON, TradeSymbolsEnum.MACHINERY, TradeSymbolsEnum.URANITE],
        [TradeSymbolsEnum.MODULE_SHIELD_GENERATOR_II] = [TradeSymbolsEnum.ALUMINUM, TradeSymbolsEnum.MACHINERY, TradeSymbolsEnum.URANITE],
        [TradeSymbolsEnum.MOUNT_SURVEYOR_III] = [TradeSymbolsEnum.PLATINUM, TradeSymbolsEnum.MACHINERY, TradeSymbolsEnum.ADVANCED_CIRCUITRY],
        [TradeSymbolsEnum.MOUNT_SENSOR_ARRAY_III] = [
           TradeSymbolsEnum.PLATINUM,
           TradeSymbolsEnum.MACHINERY,
           TradeSymbolsEnum.ADVANCED_CIRCUITRY,
           TradeSymbolsEnum.URANITE,
           ],
        [TradeSymbolsEnum.MOUNT_MINING_LASER_III] = [
           TradeSymbolsEnum.PLATINUM,
           TradeSymbolsEnum.MACHINERY,
           TradeSymbolsEnum.ADVANCED_CIRCUITRY,
           TradeSymbolsEnum.URANITE,
           ],

        [TradeSymbolsEnum.SHIP_PROBE] = SHIP_IMPORTS,
        [TradeSymbolsEnum.SHIP_MINING_DRONE] = SHIP_IMPORTS,
        [TradeSymbolsEnum.SHIP_SIPHON_DRONE] = SHIP_IMPORTS,
        [TradeSymbolsEnum.SHIP_LIGHT_HAULER] = SHIP_IMPORTS,
        [TradeSymbolsEnum.SHIP_COMMAND_FRIGATE] = SHIP_IMPORTS,
        [TradeSymbolsEnum.SHIP_INTERCEPTOR] = SHIP_IMPORTS,
        [TradeSymbolsEnum.SHIP_EXPLORER] = SHIP_IMPORTS,
        [TradeSymbolsEnum.SHIP_LIGHT_SHUTTLE] = SHIP_IMPORTS,
        [TradeSymbolsEnum.SHIP_HEAVY_FREIGHTER] = SHIP_IMPORTS,
        [TradeSymbolsEnum.SHIP_ORE_HOUND] = SHIP_IMPORTS,
        [TradeSymbolsEnum.SHIP_REFINING_FREIGHTER] = SHIP_IMPORTS,
        [TradeSymbolsEnum.SHIP_SURVEYOR] = SHIP_IMPORTS,
    };
}